export const doctors = [
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Dermatologist",
    fees: "$100",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Cardiologist",
    fees: "$120",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "3",
    name: "Dr. Emily Johnson",
    specialty: "Neurologist",
    fees: "$150",
    timing: "11:00 AM - 3:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "4",
    name: "Dr. Michael Brown",
    specialty: "Pediatrician",
    fees: "$80",
    timing: "8:00 AM - 12:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "5",
    name: "Dr. Sarah Wilson",
    specialty: "Orthopedic",
    fees: "$130",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "6",
    name: "Dr. David Lee",
    specialty: "Psychiatrist",
    fees: "$110",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "7",
    name: "Dr. Laura Martinez",
    specialty: "Gynecologist",
    fees: "$90",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "8",
    name: "Dr. James Anderson",
    specialty: "Oncologist",
    fees: "$200",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "9",
    name: "Dr. Patricia Thomas",
    specialty: "Dentist",
    fees: "$70",
    timing: "8:00 AM - 12:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "10",
    name: "Dr. Robert Garcia",
    specialty: "Ophthalmologist",
    fees: "$85",
    timing: "11:00 AM - 3:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Dermatologists
  {
    id: "11",
    name: "Dr. Alice Cooper",
    specialty: "Dermatologist",
    fees: "$105",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "12",
    name: "Dr. Mark Taylor",
    specialty: "Dermatologist",
    fees: "$110",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "13",
    name: "Dr. Rachel Green",
    specialty: "Dermatologist",
    fees: "$115",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "14",
    name: "Dr. Steven King",
    specialty: "Dermatologist",
    fees: "$95",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Cardiologists
  {
    id: "15",
    name: "Dr. Olivia White",
    specialty: "Cardiologist",
    fees: "$125",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "16",
    name: "Dr. Ethan Harris",
    specialty: "Cardiologist",
    fees: "$130",
    timing: "8:00 AM - 12:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "17",
    name: "Dr. Noah Wilson",
    specialty: "Cardiologist",
    fees: "$140",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "18",
    name: "Dr. Ava Martin",
    specialty: "Cardiologist",
    fees: "$135",
    timing: "3:00 PM - 7:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Neurologists
  {
    id: "19",
    name: "Dr. Sophia Clark",
    specialty: "Neurologist",
    fees: "$155",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "20",
    name: "Dr. Liam Walker",
    specialty: "Neurologist",
    fees: "$160",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "21",
    name: "Dr. Mia Adams",
    specialty: "Neurologist",
    fees: "$165",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "22",
    name: "Dr. Lucas Scott",
    specialty: "Neurologist",
    fees: "$170",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Pediatricians
  {
    id: "23",
    name: "Dr. Emma Davis",
    specialty: "Pediatrician",
    fees: "$85",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "24",
    name: "Dr. Oliver Miller",
    specialty: "Pediatrician",
    fees: "$75",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "25",
    name: "Dr. Charlotte Wilson",
    specialty: "Pediatrician",
    fees: "$90",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "26",
    name: "Dr. Benjamin Moore",
    specialty: "Pediatrician",
    fees: "$80",
    timing: "8:00 AM - 12:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Orthopedics
  {
    id: "27",
    name: "Dr. Henry Taylor",
    specialty: "Orthopedic",
    fees: "$140",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "28",
    name: "Dr. Amelia Carter",
    specialty: "Orthopedic",
    fees: "$135",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "29",
    name: "Dr. William Hall",
    specialty: "Orthopedic",
    fees: "$145",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "30",
    name: "Dr. Evelyn Young",
    specialty: "Orthopedic",
    fees: "$150",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Psychiatrists
  {
    id: "31",
    name: "Dr. Daniel Allen",
    specialty: "Psychiatrist",
    fees: "$115",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "32",
    name: "Dr. Harper Wright",
    specialty: "Psychiatrist",
    fees: "$120",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "33",
    name: "Dr. Alexander Lopez",
    specialty: "Psychiatrist",
    fees: "$105",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "34",
    name: "Dr. Abigail Hill",
    specialty: "Psychiatrist",
    fees: "$125",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Gynecologists
  {
    id: "35",
    name: "Dr. Jack Rivera",
    specialty: "Gynecologist",
    fees: "$95",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "36",
    name: "Dr. Scarlett Baker",
    specialty: "Gynecologist",
    fees: "$100",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "37",
    name: "Dr. Samuel Cook",
    specialty: "Gynecologist",
    fees: "$85",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "38",
    name: "Dr. Victoria Reed",
    specialty: "Gynecologist",
    fees: "$90",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Oncologists
  {
    id: "39",
    name: "Dr. Christopher Bell",
    specialty: "Oncologist",
    fees: "$210",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "40",
    name: "Dr. Madison Kelly",
    specialty: "Oncologist",
    fees: "$220",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "41",
    name: "Dr. Andrew Howard",
    specialty: "Oncologist",
    fees: "$205",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "42",
    name: "Dr. Elizabeth Ward",
    specialty: "Oncologist",
    fees: "$215",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Dentists
  {
    id: "43",
    name: "Dr. Dylan Cox",
    specialty: "Dentist",
    fees: "$75",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "44",
    name: "Dr. Chloe Murphy",
    specialty: "Dentist",
    fees: "$65",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "45",
    name: "Dr. Joshua Bailey",
    specialty: "Dentist",
    fees: "$80",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "46",
    name: "Dr. Zoey Richardson",
    specialty: "Dentist",
    fees: "$70",
    timing: "8:00 AM - 12:00 PM",
    image: "https://via.placeholder.com/100",
  },
  // Ophthalmologists
  {
    id: "47",
    name: "Dr. Nathan Wood",
    specialty: "Ophthalmologist",
    fees: "$90",
    timing: "9:00 AM - 1:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "48",
    name: "Dr. Lily Bennett",
    specialty: "Ophthalmologist",
    fees: "$95",
    timing: "1:00 PM - 5:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "49",
    name: "Dr. Caleb Coleman",
    specialty: "Ophthalmologist",
    fees: "$85",
    timing: "10:00 AM - 2:00 PM",
    image: "https://via.placeholder.com/100",
  },
  {
    id: "50",
    name: "Dr. Hannah Foster",
    specialty: "Ophthalmologist",
    fees: "$88",
    timing: "2:00 PM - 6:00 PM",
    image: "https://via.placeholder.com/100",
  },
];
